# Generated by Django 5.0.2 on 2024-02-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Phone_No', models.BigIntegerField()),
                ('Message', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_no', models.BigIntegerField()),
                ('Password', models.CharField(max_length=30)),
                ('Role', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField()),
                ('Rating', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(upload_to='photos')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Complain_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('Complain_Datetime', models.DateTimeField(auto_now=True)),
                ('Complain_Status', models.CharField(max_length=30)),
                ('Loging_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total_Amount', models.FloatField()),
                ('order_id', models.IntegerField(null=True)),
                ('Cart_Status', models.CharField(choices=[('Pending', 'Pending'), ('CONFIRMED', 'CONFIRMED')], max_length=50)),
                ('Login_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Amount', models.IntegerField()),
                ('Order_Datetime', models.DateTimeField(auto_now=True)),
                ('Order_Status', models.CharField(max_length=10)),
                ('Cart_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cart_table')),
                ('Login_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_id', models.CharField(max_length=10)),
                ('Payment_Type', models.CharField(max_length=30)),
                ('Payment_Status', models.CharField(max_length=30)),
                ('Payment_Datetime', models.DateTimeField(auto_now=True)),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_table')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('nameoncard', models.CharField(max_length=30)),
                ('cvv', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.payment_table')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Description', models.TextField()),
                ('Product_Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image', models.ImageField(upload_to='photos')),
                ('Product_Status', models.CharField(choices=[('0', 'Out of stock'), ('1', 'Instock')], max_length=20)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category_table')),
                ('Login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='cart_table',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_table'),
        ),
    ]
