# Generated by Django 5.0.1 on 2024-02-27 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_table',
            name='Login_id',
        ),
        migrations.AddField(
            model_name='product_table',
            name='Vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.AlterField(
            model_name='cart_table',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_table'),
        ),
    ]
