# Generated by Django 5.0.1 on 2024-02-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_table_login_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_table',
            old_name='Vendor_id',
            new_name='Login_id',
        ),
    ]
