# Generated by Django 5.0.1 on 2024-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_vendor_id_product_table_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='Image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
