# Generated by Django 5.0.1 on 2024-03-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='Cart_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart_table'),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Login_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Order_Datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Order_Status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_table',
            name='Total_Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='Login_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='Order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.order_table'),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='Payment_Datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='Payment_Status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='Payment_Type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
