# Generated by Django 5.0.1 on 2024-03-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_order_table_cart_id_alter_order_table_login_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_table',
            options={'verbose_name': 'Login Detail'},
        ),
    ]
