# Generated by Django 5.0.1 on 2024-03-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_login_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_table',
            options={'verbose_name': 'Login Detail', 'verbose_name_plural': 'Login Details'},
        ),
    ]
