# Generated by Django 5.0.1 on 2024-03-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_login_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_table',
            options={'verbose_name': 'Card Detail', 'verbose_name_plural': 'Card Details'},
        ),
        migrations.AlterModelOptions(
            name='cart_table',
            options={'verbose_name': 'Cart Detail', 'verbose_name_plural': 'Cart Details'},
        ),
        migrations.AlterModelOptions(
            name='category_table',
            options={'verbose_name': 'Category Detail', 'verbose_name_plural': 'Category Details'},
        ),
        migrations.AlterModelOptions(
            name='complain_table',
            options={'verbose_name': 'Complain Detail', 'verbose_name_plural': 'Complain Details'},
        ),
        migrations.AlterModelOptions(
            name='contact_us_table',
            options={'verbose_name': 'Contact Us Detail', 'verbose_name_plural': 'Contact Us Details'},
        ),
        migrations.AlterModelOptions(
            name='detail_table',
            options={'verbose_name': 'Profile Detail', 'verbose_name_plural': 'Profile Details'},
        ),
        migrations.AlterModelOptions(
            name='feedback_table',
            options={'verbose_name': 'Feedback Detail', 'verbose_name_plural': 'Feedback Details'},
        ),
        migrations.AlterModelOptions(
            name='order_table',
            options={'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='payment_table',
            options={'verbose_name': 'Payment Detail', 'verbose_name_plural': 'Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='product_table',
            options={'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
    ]
