# Generated by Django 5.0.1 on 2024-03-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_card_table_options_alter_cart_table_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_table',
            options={'verbose_name': 'Card Detail'},
        ),
    ]
