# Generated by Django 5.0.1 on 2024-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_card_table_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='Status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=30),
        ),
    ]
