# Generated by Django 5.0.1 on 2024-03-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_login_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='User_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
