# Generated by Django 5.0.1 on 2024-03-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_login_table_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_table',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment_table',
            name='trans_id',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
