# Generated by Django 5.0.1 on 2024-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_payment_table_amount_payment_table_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_table',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
    ]
