# Generated by Django 5.0.1 on 2024-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_card_table_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='card_balance',
            field=models.IntegerField(default=100000, null=True),
        ),
    ]
