# Generated by Django 5.0.1 on 2024-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_cart_table_card_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_table',
            name='card_balance',
        ),
        migrations.AddField(
            model_name='card_table',
            name='card_balance',
            field=models.IntegerField(default=100000, null=True),
        ),
    ]
