# Generated by Django 5.0.1 on 2024-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_cart_table_card_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_table',
            name='exp_date',
            field=models.IntegerField(null=True),
        ),
    ]
