# Generated by Django 5.0.1 on 2024-03-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_card_table_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_table',
            name='payment_id',
        ),
    ]
