# Generated by Django 5.0.1 on 2024-03-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_card_table_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_table',
            name='User',
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='User_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='Review',
            field=models.TextField(null=True),
        ),
    ]
