# Generated by Django 5.0.1 on 2024-03-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_feedback_table_user_feedback_table_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_table',
            old_name='Review',
            new_name='Comment',
        ),
    ]
