# Generated by Django 5.0 on 2024-03-29 06:52

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_review_feedback_table_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('card_cvv', models.CharField(max_length=50)),
                ('exp_date', models.CharField(max_length=50)),
                ('card_balance', models.IntegerField(default=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.IntegerField(default=0)),
                ('Address', models.TextField()),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed')], max_length=50)),
                ('Payment_status', models.CharField(max_length=30)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('Login_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.DeleteModel(
            name='Card_Table',
        ),
        migrations.RemoveField(
            model_name='payment_table',
            name='Order_id',
        ),
        migrations.AlterModelOptions(
            name='cart_table',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedback_table',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment_table',
            options={},
        ),
        migrations.RenameField(
            model_name='feedback_table',
            old_name='User_email',
            new_name='Login_ID',
        ),
        migrations.RemoveField(
            model_name='cart_table',
            name='Cart_Status',
        ),
        migrations.RemoveField(
            model_name='cart_table',
            name='Total_Amount',
        ),
        migrations.RemoveField(
            model_name='cart_table',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='feedback_table',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='feedback_table',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='feedback_table',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='payment_table',
            name='Payment_Datetime',
        ),
        migrations.RemoveField(
            model_name='payment_table',
            name='Payment_Status',
        ),
        migrations.RemoveField(
            model_name='payment_table',
            name='Payment_Type',
        ),
        migrations.RemoveField(
            model_name='payment_table',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='cart_table',
            name='Order_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart_table',
            name='Price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment_table',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_table',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment_table',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='Login_id',
            field=models.CharField(max_length=10, null=True, verbose_name=myapp.models.Login_Table),
        ),
        migrations.AlterField(
            model_name='payment_table',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='order_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product_order'),
        ),
        migrations.DeleteModel(
            name='Order_Table',
        ),
        migrations.AddField(
            model_name='payment_table',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.product_order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_table',
            name='Order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback_table',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment_table',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=30),
        ),
    ]
