# Generated by Django 5.0 on 2024-03-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_carddetail_product_order_delete_card_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='Total_Amount',
            field=models.IntegerField(default=200),
        ),
    ]
