# Generated by Django 5.0 on 2024-03-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_cart_table_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_table',
            options={},
        ),
    ]
