# Generated by Django 5.0 on 2024-03-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_login_table_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_table',
            old_name='Login_id',
            new_name='Login_ID',
        ),
    ]
