# Generated by Django 5.0 on 2024-03-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_login_id_payment_table_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='Login_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
    ]
