# Generated by Django 5.0 on 2024-03-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_payment_table_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_table',
            name='Login_id',
        ),
        migrations.AddField(
            model_name='product_table',
            name='Vendor',
            field=models.ForeignKey(default='', limit_choices_to={'Role': 'Vendor'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.AlterField(
            model_name='login_table',
            name='Role',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('User', 'User')], default='', max_length=30),
        ),
    ]
