# Generated by Django 5.0 on 2024-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_product_table_login_id_product_table_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='Role',
            field=models.CharField(default='', max_length=30),
        ),
    ]
