# Generated by Django 5.0.1 on 2024-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_login_table_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_table',
            options={'verbose_name': 'Cart Detail', 'verbose_name_plural': 'Cart Details'},
        ),
        migrations.AlterModelOptions(
            name='feedback_table',
            options={'verbose_name': 'Feedback Detail', 'verbose_name_plural': 'Feedback Details'},
        ),
        migrations.AlterModelOptions(
            name='login_table',
            options={'verbose_name': 'Login Detail', 'verbose_name_plural': 'Login Details'},
        ),
        migrations.AlterModelOptions(
            name='payment_table',
            options={'verbose_name': 'Payment Detail', 'verbose_name_plural': 'Payment Details'},
        ),
        migrations.AddField(
            model_name='login_table',
            name='First_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='login_table',
            name='Last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
