# Generated by Django 5.0.1 on 2024-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_cart_table_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_table',
            name='First_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact_us_table',
            name='Last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
