# Generated by Django 5.0.1 on 2024-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_contact_us_table_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='Image1',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='Image2',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='Image3',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
