# Generated by Django 5.0.1 on 2024-04-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_product_table_image1_product_table_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='Product_Name',
            field=models.CharField(max_length=100),
        ),
    ]
